// Generated by https://quicktype.io

import { Usuario } from "../models/usuario.models";

export interface GetUsuarios {
    ok?:       boolean;
    usuarios: Usuario[]; 
    uid?:      string;
    total:    number;
}